# https://taskfile.dev

version: '3'

vars:
  CONFIG_PATH: "{{.USER_WORKING_DIR}}/.prolog"
  CONTAINER_RUNTIME: podman
  IMAGE_TAG: 0.0.1

tasks:
  run:server:
    cmds:
      - go run cmd/server/main.go
    silent: false
  build-image:
    cmds:
      - '{{.CONTAINER_RUNTIME}} build -t github.com/gray-adeyi/prolog:{{.IMAGE_TAG}} .'
  compile:
    cmds:
      - protoc api/v1/*.proto --go_out=. --go-grpc_out=. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --proto_path=.
  test:
    cmds:
      - task: copy-model-conf
      - task: copy-policy-conf
      - task: fmt
      - CONFIG_DIR={{.CONFIG_PATH}} go test ./internal/... -race
  copy-model-conf:
    cmds:
      - cp test/model.conf {{.CONFIG_PATH}}/model.conf
  copy-policy-conf:
    cmds:
      - cp test/policy.csv {{.CONFIG_PATH}}/policy.csv
  fmt:
    cmds:
      - go fmt ./...
  init-config:
    cmds:
      - mkdir -p {{.CONFIG_PATH}}
  gencert:
    cmds:
      - task: init-config
      - cfssl gencert -initca test/ca-csr.json | cfssljson -bare ca
      - cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=test/ca-config.json -profile=server test/server-csr.json | cfssljson -bare server
      - cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=test/ca-config.json -profile=client -cn="root" test/client-csr.json | cfssljson -bare root-client
      - cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=test/ca-config.json -profile=client -cn="nobody" test/client-csr.json | cfssljson -bare nobody-client
      - mv *.pem *.csr {{.CONFIG_PATH}}