# https://taskfile.dev

version: '3'

tasks:
  run:server:
    cmds:
      - go run cmd/server/main.go
    silent: false
  compile:
    cmds:
      - protoc api/v1/*.proto --go_out=. --go-grpc_out=. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --proto_path=.
  test:
    cmds:
      - go test -race ./internal/...
  fmt:
    cmds:
      - go fmt ./...
